services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Oveleon\ContaoAdvancedForm\:
    resource: '../src/'
    exclude: '../src/{Model,DependencyInjection,Resources,FormHandler.php}'
