services:
    _defaults:
        autoconfigure: true

    contao_advanced_form.form_page_manager:
        class: Oveleon\ContaoAdvancedForm\Service\FormPage\FormPageManagerFactory
        arguments:
            - '@request_stack'
            - '@Codefog\HasteBundle\UrlParser'


    # Autowiring aliases
    Oveleon\ContaoAdvancedForm\Service\FormPage\FormPageManagerFactory: '@contao_advanced_form.form_page_manager'
